version: "3.9"

services:
  backend:
    build: ./backend
    container_name: afterus-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - afterus-network

  frontend:
    build: ./frontend
    container_name: afterus-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - afterus-network

networks:
  afterus-network: